apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.31.2 (HEAD)
  labels:
    io.kompose.service: votey-backend
  name: votey-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: votey-backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s
        kompose.version: 1.31.2 (HEAD)
      labels:
        io.kompose.network/votey-default: "true"
        io.kompose.service: votey-backend
    spec:
      containers:
        - env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: votey
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: votey
                  key: CLIENT_SECRET
            - name: SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: votey
                  key: SIGNING_SECRET
            - name: DATABASE_URL
              value: postgres://postgres:postgres@db:5432/postgres
            - name: FLASK_ENV
              value: production
          image: votey-backend
          name: votey-backend
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
      restartPolicy: Always