apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.31.2 (HEAD)
  labels:
    io.kompose.service: votey-db
  name: votey-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: votey-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s
        kompose.version: 1.31.2 (HEAD)
      labels:
        io.kompose.network/votey-default: "true"
        io.kompose.service: votey-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          name: votey-db
          resources: {}
      restartPolicy: Always
status: {}
